#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for utils/init
#
# IDENTIFICATION
#    src/backend/utils/init/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/utils/init
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	auth_lock.o \
	globals.o \
	miscinit.o \
	postinit.o \
	usercontext.o

include $(top_srcdir)/src/backend/common.mk
